# Generated by Django 3.2.15 on 2022-09-06 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='posts.comment'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'comment', 'comment_id')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='id_of_comment',
        ),
    ]
