# Generated by Django 3.2.15 on 2022-08-26 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.comment')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(null=True)),
                ('url', models.URLField(blank=True, default='', max_length=120)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('locked', models.BooleanField(blank=True, default=False)),
                ('is_stickied', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.category')),
            ],
            options={
                'abstract': False,
            },
            bases=('posts.comment',),
        ),
    ]
