# Generated by Django 3.2.15 on 2022-08-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
